# AI_agents/publish_agent.py
import subprocess
import json
from pathlib import Path
from .ai_utils import APP_GEN_DIR, read_utf8

def run_command(cmd, cwd=None):
    """Execute shell command and return output"""
    result = subprocess.run(
        cmd,
        shell=True,
        cwd=cwd,
        capture_output=True,
        text=True
    )
    if result.returncode != 0:
        print(f"Command failed: {cmd}")
        print(f"Error: {result.stderr}")
    return result

def check_gh_auth():
    """Check if gh CLI is authenticated, if not prompt login"""
    check_auth = run_command("gh auth status")

    if check_auth.returncode != 0:
        print("GitHub CLI not authenticated. Please login...")
        login_result = run_command("gh auth login")
        if login_result.returncode != 0:
            print("Failed to authenticate with GitHub CLI")
            return False
    return True

def main():
    print("=== STEP5: Publish to GitHub and Deploy ===")

    # Check GitHub authentication
    if not check_gh_auth():
        print("Cannot proceed without GitHub authentication")
        return

    # Read design to get app name
    design = read_utf8("design.yaml")

    # Extract app name from design or use default
    import re
    match = re.search(r'name:\s*(\S+)', design)
    if match:
        app_name = match.group(1).lower().replace('_', '-')
    else:
        app_name = "generated-app"

    print(f"Publishing app: {app_name}")

    # 1. Initialize git in generated_app if not already
    git_init = run_command("git init", cwd=APP_GEN_DIR)

    # 2. Create .gitignore
    gitignore_content = """
# .NET
bin/
obj/
*.db
*.db-shm
*.db-wal

# Node
node_modules/
dist/
.vite/

# IDEs
.vscode/
.idea/
*.swp
*.swo

# OS
.DS_Store
Thumbs.db

# Env
.env
.env.local
"""
    gitignore_path = APP_GEN_DIR / ".gitignore"
    with open(gitignore_path, "w") as f:
        f.write(gitignore_content)

    # 3. Create README.md for the generated app
    readme_content = f"""# {app_name}

Generated by AI Factory

## Structure
- `backend/` - .NET 8 Minimal API
- `frontend/` - React 18 + TypeScript + Tailwind
- `.github/workflows/` - CI/CD pipelines

## Local Development

### Backend
```bash
cd backend
dotnet run
```

### Frontend
```bash
cd frontend
npm install
npm run dev
```

## Deployment
See `.github/workflows/deploy.yml` for automated deployment configuration.
"""
    readme_path = APP_GEN_DIR / "README.md"
    with open(readme_path, "w") as f:
        f.write(readme_content)

    # 4. Add and commit all files
    run_command("git add .", cwd=APP_GEN_DIR)
    run_command('git commit -m "Initial commit: AI-generated app"', cwd=APP_GEN_DIR)

    # 5. Create GitHub repository using gh CLI
    print(f"Creating GitHub repository: {app_name}")
    create_repo = run_command(
        f'gh repo create {app_name} --public --source . --remote origin --push',
        cwd=APP_GEN_DIR
    )

    if create_repo.returncode == 0:
        print(f"OK Repository created and pushed: https://github.com/$(gh api user -q .login)/{app_name}")

        # 6. Deploy frontend to Vercel (free)
        print("\nDeploying frontend to Vercel...")
        print("Installing Vercel CLI if needed...")
        run_command("npm install -g vercel", cwd=APP_GEN_DIR / "frontend")

        # Create vercel.json config
        vercel_config = {
            "buildCommand": "npm run build",
            "outputDirectory": "dist",
            "framework": "vite",
            "rewrites": [
                {
                    "source": "/api/:path*",
                    "destination": "http://localhost:5000/api/:path*"
                }
            ]
        }
        vercel_path = APP_GEN_DIR / "frontend" / "vercel.json"
        with open(vercel_path, "w") as f:
            json.dump(vercel_config, f, indent=2)

        print("\nTo deploy to Vercel, run:")
        print(f"  cd {APP_GEN_DIR / 'frontend'}")
        print("  vercel --prod")

        # 7. Deploy backend instructions
        print("\nBackend deployment options:")
        print("1. Railway.app (free tier): https://railway.app")
        print("2. Render.com (free tier): https://render.com")
        print("3. Fly.io (free tier): https://fly.io")
        print("\nRun in backend directory:")
        print("  flyctl launch  # for Fly.io")
        print("  OR connect your GitHub repo to Railway/Render dashboard")
    else:
        print("Failed to create GitHub repository")
        print("Make sure 'gh' CLI is installed and authenticated: gh auth login")

if __name__ == "__main__":
    main()
