# AI_agents/uxui_agent.py
from .ai_utils import call_ai, write_utf8, read_utf8, strip_markdown_fences
import json
from datetime import datetime

def main():
    print("=== STEP1.5: UX/UI Design System Generation ===")

    # Read the design.yaml generated by architect_agent
    try:
        design_yaml = read_utf8("design.yaml")
        print(f"INFO Design YAML loaded ({len(design_yaml)} chars)")
    except FileNotFoundError:
        print("ERROR: design.yaml not found. Run architect_agent first.")
        return

    # Generate ultra-modern design system following 2026 trends
    prompt_uxui = f"""
You are an ELITE UX/UI designer specializing in 2026 luxury design trends.
You've won Awwwards, CSS Design Awards, and design recognition from Apple, Stripe, Linear, Vercel, and Framer.

CONTEXT FROM ARCHITECTURE:
{design_yaml}

DESIGN PHILOSOPHY - 6 PILLARS:

1. **Glassmorphism**: Frosted glass effect with backdrop-filter: blur(20px), semi-transparent backgrounds (rgba with 0.1-0.2 alpha), white text on dark glass
2. **Luxury Dark Mode**: Base background rgb(10, 10, 20) or #0a0a14, high-contrast white text (#ffffff), accent text #e0e0ff
3. **Premium Gradients**: Main gradient linear-gradient(135deg, #667eea, #764ba2) for buttons and accents; secondary gradients with blues and purples
4. **Micro-interactions**: All transitions 0.3s cubic-bezier(0.4, 0, 0.2, 1), hover effects transform: translateY(-2px), glow shadows on buttons
5. **Typography**: Geist font for headings (weight 600-700), Inter for body text (weight 400-500), scale from 0.75rem to 3rem
6. **Animations**: fadeIn (0.6s ease-out), slideUp (0.5s ease-out, transform translateY), scaleIn (0.4s ease-out), shimmer (loading state)

TECHNICAL CONSTRAINTS:
- Output ONLY valid JSON, no markdown or code blocks
- All property names in camelCase
- All values must have proper CSS units (px, rem, %, #hex, rgba, etc.)
- No external dependencies or npm packages - CSS and HTML only
- Accessibility: WCAG 2.1 AA compliance (contrast ratios 4.5:1+), focus rings visible, touch targets 44px+

DESIGN SYSTEM JSON STRUCTURE:
{{
  "metadata": {{
    "name": "Modern Design System 2026",
    "version": "1.0.0",
    "theme": "dark-luxury",
    "generated_at": "ISO8601_TIMESTAMP"
  }},
  "design_tokens": {{
    "colors": {{
      "primary": "#667eea",
      "primaryHover": "#764ba2",
      "accent": "#764ba2",
      "background": "rgb(10, 10, 20)",
      "backgroundSecondary": "rgb(20, 20, 30)",
      "backgroundTertiary": "rgb(30, 30, 45)",
      "glass": "rgba(255, 255, 255, 0.1)",
      "glassBorder": "rgba(255, 255, 255, 0.2)",
      "text": "#ffffff",
      "textSecondary": "#e0e0ff",
      "textTertiary": "#a0a0b0",
      "success": "#10b981",
      "warning": "#f59e0b",
      "error": "#ef4444",
      "gradient": "linear-gradient(135deg, #667eea, #764ba2)"
    }},
    "typography": {{
      "fonts": {{
        "heading": "'Geist', -apple-system, BlinkMacSystemFont, sans-serif",
        "body": "'Inter', -apple-system, BlinkMacSystemFont, sans-serif"
      }},
      "sizes": {{
        "xs": "0.75rem",
        "sm": "0.875rem",
        "base": "1rem",
        "lg": "1.125rem",
        "xl": "1.25rem",
        "2xl": "1.5rem",
        "3xl": "2rem",
        "4xl": "2.5rem"
      }},
      "weights": {{
        "light": 300,
        "normal": 400,
        "medium": 500,
        "semibold": 600,
        "bold": 700
      }},
      "lineHeights": {{
        "tight": 1.2,
        "normal": 1.5,
        "relaxed": 1.75
      }}
    }},
    "spacing": {{
      "xs": "0.25rem",
      "sm": "0.5rem",
      "md": "1rem",
      "lg": "1.5rem",
      "xl": "2rem",
      "2xl": "3rem",
      "3xl": "4rem"
    }},
    "shadows": {{
      "sm": "0 1px 2px 0 rgba(0, 0, 0, 0.05)",
      "md": "0 4px 6px -1px rgba(0, 0, 0, 0.1)",
      "lg": "0 10px 15px -3px rgba(0, 0, 0, 0.2)",
      "xl": "0 20px 25px -5px rgba(0, 0, 0, 0.3)",
      "glow": "0 0 20px rgba(102, 126, 234, 0.4)",
      "inner": "inset 0 2px 4px 0 rgba(0, 0, 0, 0.2)"
    }},
    "borders": {{
      "radiusSm": "0.375rem",
      "radiusMd": "0.5rem",
      "radiusLg": "0.75rem",
      "radiusXl": "1rem",
      "radiusFull": "9999px",
      "width": "1px"
    }},
    "effects": {{
      "glassmorphism": "backdrop-filter: blur(20px); background: rgba(255, 255, 255, 0.1); border: 1px solid rgba(255, 255, 255, 0.2);",
      "gradientPrimary": "linear-gradient(135deg, #667eea, #764ba2)",
      "gradientSecondary": "linear-gradient(135deg, #764ba2, #667eea)"
    }}
  }},
  "layout": {{
    "container": {{
      "maxWidth": "1280px",
      "padding": "1rem"
    }},
    "grid": {{
      "columns": 12,
      "gap": "1.5rem"
    }},
    "breakpoints": {{
      "mobile": "0px",
      "tablet": "768px",
      "desktop": "1024px",
      "wide": "1280px"
    }}
  }},
  "components": {{
    "button": {{
      "base": {{
        "padding": "0.75rem 1.5rem",
        "borderRadius": "0.5rem",
        "fontSize": "1rem",
        "fontWeight": 600,
        "transition": "all 0.3s cubic-bezier(0.4, 0, 0.2, 1)",
        "cursor": "pointer",
        "border": "none",
        "minHeight": "44px"
      }},
      "variants": {{
        "primary": {{
          "background": "linear-gradient(135deg, #667eea, #764ba2)",
          "color": "#ffffff",
          "boxShadow": "0 0 20px rgba(102, 126, 234, 0.4)",
          "hover": {{
            "transform": "translateY(-2px)",
            "boxShadow": "0 0 30px rgba(102, 126, 234, 0.6)"
          }},
          "active": {{
            "transform": "translateY(0)"
          }}
        }},
        "secondary": {{
          "background": "rgba(255, 255, 255, 0.1)",
          "color": "#ffffff",
          "border": "1px solid rgba(255, 255, 255, 0.2)",
          "hover": {{
            "background": "rgba(255, 255, 255, 0.15)",
            "transform": "translateY(-2px)"
          }}
        }},
        "ghost": {{
          "background": "transparent",
          "color": "#e0e0ff",
          "hover": {{
            "background": "rgba(255, 255, 255, 0.05)",
            "transform": "translateY(-2px)"
          }}
        }}
      }}
    }},
    "card": {{
      "base": {{
        "borderRadius": "0.75rem",
        "padding": "1.5rem",
        "transition": "all 0.3s cubic-bezier(0.4, 0, 0.2, 1)"
      }},
      "variants": {{
        "elevated": {{
          "background": "rgba(255, 255, 255, 0.05)",
          "backdropFilter": "blur(20px)",
          "border": "1px solid rgba(255, 255, 255, 0.1)",
          "boxShadow": "0 10px 15px -3px rgba(0, 0, 0, 0.2)",
          "hover": {{
            "transform": "translateY(-4px)",
            "boxShadow": "0 20px 25px -5px rgba(0, 0, 0, 0.3)"
          }}
        }},
        "flat": {{
          "background": "rgb(20, 20, 30)",
          "border": "1px solid rgba(255, 255, 255, 0.1)",
          "hover": {{
            "background": "rgb(30, 30, 45)"
          }}
        }}
      }}
    }},
    "input": {{
      "base": {{
        "padding": "0.75rem 1rem",
        "borderRadius": "0.5rem",
        "fontSize": "1rem",
        "background": "rgba(255, 255, 255, 0.05)",
        "border": "1px solid rgba(255, 255, 255, 0.2)",
        "color": "#ffffff",
        "transition": "all 0.3s cubic-bezier(0.4, 0, 0.2, 1)",
        "minHeight": "44px"
      }},
      "states": {{
        "focus": {{
          "background": "rgba(255, 255, 255, 0.08)",
          "border": "1px solid rgba(102, 126, 234, 0.5)",
          "outline": "none",
          "boxShadow": "0 0 10px rgba(102, 126, 234, 0.3)"
        }},
        "error": {{
          "border": "1px solid #ef4444",
          "boxShadow": "0 0 10px rgba(239, 68, 68, 0.3)"
        }}
      }}
    }},
    "modal": {{
      "overlay": {{
        "background": "rgba(0, 0, 0, 0.5)",
        "backdropFilter": "blur(5px)",
        "transition": "all 0.3s cubic-bezier(0.4, 0, 0.2, 1)"
      }},
      "content": {{
        "background": "rgb(20, 20, 30)",
        "border": "1px solid rgba(255, 255, 255, 0.1)",
        "borderRadius": "1rem",
        "padding": "2rem",
        "boxShadow": "0 20px 25px -5px rgba(0, 0, 0, 0.5)",
        "maxWidth": "600px"
      }}
    }}
  }},
  "animations": {{
    "fadeIn": {{
      "duration": "0.6s",
      "timing": "ease-out",
      "keyframes": {{"0%": "opacity: 0;", "100%": "opacity: 1;"}}
    }},
    "slideUp": {{
      "duration": "0.5s",
      "timing": "ease-out",
      "keyframes": {{"0%": "opacity: 0; transform: translateY(20px);", "100%": "opacity: 1; transform: translateY(0);"}}
    }},
    "scaleIn": {{
      "duration": "0.4s",
      "timing": "ease-out",
      "keyframes": {{"0%": "opacity: 0; transform: scale(0.95);", "100%": "opacity: 1; transform: scale(1);"}}
    }},
    "shimmer": {{
      "duration": "2s",
      "timing": "infinite",
      "keyframes": {{"0%": "background-position: -1000px 0;", "100%": "background-position: 1000px 0;"}}
    }}
  }},
  "accessibility": {{
    "focusRing": {{
      "outline": "2px solid #667eea",
      "outlineOffset": "2px"
    }},
    "minContrastRatio": "4.5:1",
    "touchTargetMin": "44px",
    "focusVisible": "outline: 2px dashed #667eea; outline-offset: 2px;"
  }},
  "wireframes": {{
    "header": {{
      "background": "rgb(10, 10, 20)",
      "padding": "1rem 1.5rem",
      "display": "flex",
      "alignItems": "center",
      "justifyContent": "space-between"
    }},
    "hero": {{
      "background": "linear-gradient(135deg, #667eea, #764ba2)",
      "padding": "4rem 2rem",
      "textAlign": "center",
      "minHeight": "400px"
    }},
    "content": {{
      "padding": "2rem",
      "maxWidth": "1280px",
      "margin": "0 auto"
    }}
  }}
}}

Generate the complete, valid JSON design system following ALL specifications above.
Output ONLY JSON, no markdown, no code blocks, no explanations.
"""

    uxui_json_raw = call_ai(
        prompt_uxui,
        system_content="You are an elite UX/UI designer and design system expert. Output ONLY valid JSON, no markdown, no explanations. Everything in English.",
        max_tokens=8000
    )

    uxui_json_clean = strip_markdown_fences(uxui_json_raw)

    # Try to parse and validate JSON
    try:
        uxui_data = json.loads(uxui_json_clean)
        # Add/update generation timestamp
        if "metadata" not in uxui_data:
            uxui_data["metadata"] = {}
        uxui_data["metadata"]["generated_at"] = datetime.utcnow().isoformat() + "Z"
        uxui_json_final = json.dumps(uxui_data, indent=2, ensure_ascii=False)
        print(f"OK Valid JSON generated ({len(uxui_json_final)} chars)")
    except json.JSONDecodeError as e:
        print(f"WARNING Invalid JSON from AI, attempting repair: {str(e)[:100]}")
        uxui_json_final = uxui_json_clean

    write_utf8("uxui_design.json", uxui_json_final)
    print("=== STEP1.5 completed (generated_app/uxui_design.json) ===")

if __name__ == "__main__":
    main()
