"""add generation_attempt tracking

Revision ID: b644db3e3f27
Revises: 29ffc17e697b
Create Date: 2026-04-10 23:10:19.860344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b644db3e3f27'
down_revision: Union[str, Sequence[str], None] = '29ffc17e697b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generation_logs', sa.Column('generation_attempt', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('projects', sa.Column('generation_attempt', sa.Integer(), nullable=False, server_default='1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'generation_attempt')
    op.drop_column('generation_logs', 'generation_attempt')
    # ### end Alembic commands ###
